name: CI&CD

on:
  push:
    tags:
    - '*'
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: build pack
        run: |
            npm install 
            npm run build-pack
      - name: npm push
        run: |
            npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish
        env:
             NPM_TOKEN: '${{secrets.NPM_AUTH_TOKEN}}'
      - name: build dist
        run: |
            npm install 
      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.SERVER_PEM}}
        with:
          flags: '-avzr --delete'
          options: ''
          ssh_options: '-p ${{secrets.SERVER_PORT}}'
          src: 'dist/'
          dest: 'labs@${{secrets.SERVER_HOST}}:/mnt/authing/Guard/dist/'

